### ISSUE TITLE
FYI - installation (w7ent)

### ISSUE THREAD

**Issue by ljgww** [dtjm/node-multimarkdown#13]
C:\Users\user\dev\nw\viewMarkdown>npm install multimarkdown
npm WARN package.json ViewMarkdown@ No repository field.
npm http GET https://registry.npmjs.org/multimarkdown
npm http 200 https://registry.npmjs.org/multimarkdown
npm http GET https://registry.npmjs.org/multimarkdown/-/multimarkdown-0.0.15.tgz
npm http 200 https://registry.npmjs.org/multimarkdown/-/multimarkdown-0.0.15.tgz

> multimarkdown@0.0.15 preinstall C:\Users\user\dev\nw\viewMarkdown\node_modules\multimarkdown
> node-gyp configure && mkdir -p deps && cd deps && curl 'https://codeload.github.com/fletcher/peg-multimarkdown/tar.gz/3.7' | tar zxvf - && mv peg-multimarkdown-\* peg-multimarkdown && cd peg-multimarkdown && CFLAGS='-fPIC -Wall -O3 -include GLibFacade.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE' make && cd ../../ && node-gyp build

C:\Users\user\dev\nw\viewMarkdown\node_modules\multimarkdown>node "C:\nodejs\node_modules\npm\bin\node-gyp-bin\....\node_modules\node-gyp\bin\node-gyp.js" configure'curl' is not recognized as an internal or external command,operable program or batch file.
npm ERR! multimarkdown@0.0.15 preinstall: `node-gyp configure && mkdir -p deps && cd deps && curl 'https://codeload.github.com/fletcher/peg-multimarkdown/tar.gz/3.7' | tar zxvf - && mv peg-multimarkdown-* peg-multimarkdown && cd peg-multimarkdown && CFLAGS='-fPIC -Wall -O3 -include GLibFacade.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE' make && cd ../../ && node-gyp build`
npm ERR! Exit status 255
npm ERR!
npm ERR! Failed at the multimarkdown@0.0.15 preinstall script.
npm ERR! This is most likely a problem with the multimarkdown package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp configure && mkdir -p deps && cd deps && curl 'https://codeload.github.com/fletcher/peg-multimarkdown/tar.gz/3.7' | tar zxvf - && mv peg-multimarkdown-\* peg-multimarkdown && cd peg-multimarkdown && CFLAGS='-fPIC -Wall -O3 -include GLibFacade.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE' make && cd ../../ && node-gyp build
npm ERR! You can get their info via:
npm ERR!     npm owner ls multimarkdown
npm ERR! There is likely additional logging output above.

npm ERR! System Windows_NT 6.1.7601
npm ERR! command "C:\nodejs\\node.exe" "C:\nodejs\node_modules\npm\bin\npm-cli.js" "install" "multimarkdown"
npm ERR! cwd C:\Users\user\dev\nw\viewMarkdown
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.15
npm ERR! code ELIFECYCLE
npm ERR!
npm ERR! Additional logging details can be found in:
npm ERR!     C:\Users\user\dev\nw\viewMarkdown\npm-debug.log
npm ERR! not ok code 0

C:\Users\user\dev\nw\viewMarkdown>

**Comment by itajaja** [comment]
Still no way to use this package on windows? installing curl is not enough...
