### ISSUE TITLE
npm install failing on OSX 10.9.5

### ISSUE THREAD

**Issue by rob-gordon** [dtjm/node-multimarkdown#14]
I'm having trouble understanding what's going wrong from the output.
This happens when trying `npm install -g multimarkdown` and `sudo npm install -g multimarkdown`

    make: *** [Release/obj.target/multimarkdown/multimarkdown.o] Error 1
	gyp ERR! build error
	gyp ERR! stack Error: `make` failed with exit code: 2
	gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
	gyp ERR! System Darwin 13.4.0
	gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "build"
	gyp ERR! cwd /usr/local/lib/node_modules/multimarkdown
	gyp ERR! node -v v0.12.0
	gyp ERR! node-gyp -v v1.0.2
	gyp ERR! not ok
	npm ERR! Darwin 13.4.0
	npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "install" "-g" "multimarkdown"
	npm ERR! node v0.12.0
	npm ERR! npm  v2.5.1
	npm ERR! code ELIFECYCLE

	npm ERR! multimarkdown@0.0.15 preinstall: `node-gyp configure && mkdir -p deps && cd deps && curl 'https://codeload.github.com/fletcher/peg-multimarkdown/tar.gz/3.7' | tar zxvf - && mv peg-multimarkdown-* peg-multimarkdown && cd peg-multimarkdown && CFLAGS='-fPIC -Wall -O3 -include GLibFacade.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE' make && cd ../../ && node-gyp build`
	npm ERR! Exit status 1
	npm ERR!
	npm ERR! Failed at the multimarkdown@0.0.15 preinstall script 'node-gyp configure && mkdir -p deps && cd deps && curl 'https://codeload.github.com/fletcher/peg-multimarkdown/tar.gz/3.7' | tar zxvf - && mv peg-multimarkdown-* peg-multimarkdown && cd peg-multimarkdown && CFLAGS='-fPIC -Wall -O3 -include GLibFacade.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE' make && cd ../../ && node-gyp build'.
	npm ERR! This is most likely a problem with the multimarkdown package,
	npm ERR! not with npm itself.
	npm ERR! Tell the author that this fails on your system:
	npm ERR!     node-gyp configure && mkdir -p deps && cd deps && curl 'https://codeload.github.com/fletcher/peg-multimarkdown/tar.gz/3.7' | tar zxvf - && mv peg-multimarkdown-* peg-multimarkdown && cd peg-multimarkdown && CFLAGS='-fPIC -Wall -O3 -include GLibFacade.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE' make && cd ../../ && node-gyp build
	npm ERR! You can get their info via:
	npm ERR!     npm owner ls multimarkdown
	npm ERR! There is likely additional logging output above.

	npm ERR! Please include the following file with any support request:
	npm ERR!     /Users/robgordon/Documents/Ideas/npm-debug.log

**Comment by dtjm** [comment]
Sorry I don't have an installation of 10.9.5 to test on. Can you try each of the steps of the pre install script one-by-one and see which one fails?

```bash
node-gyp configure
mkdir -p deps
cd deps
'https://codeload.github.com/fletcher/peg-multimarkdown/tar.gz/3.7' | tar zxvf - 
mv peg-multimarkdown-* peg-multimarkdown
cd peg-multimarkdown
CFLAGS='-fPIC -Wall -O3 -include GLibFacade.h -I ./ -D MD_USE_GET_OPT=1 -D_GNU_SOURCE' make
cd ../../
node-gyp build
```

**Comment by rob-gordon** [comment]
It's failing on the first step

	gyp info it worked if it ends with ok
	gyp info using node-gyp@1.0.3
	gyp info using node@0.12.0 | darwin | x64
	gyp info spawn python
	gyp info spawn args [ '/usr/local/lib/node_modules/node-gyp/gyp/gyp_main.py',
	gyp info spawn args   'binding.gyp',
	gyp info spawn args   '-f',
	gyp info spawn args   'make',
	gyp info spawn args   '-I',
	gyp info spawn args   '/Users/robgordon/build/config.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/usr/local/lib/node_modules/node-gyp/addon.gypi',
	gyp info spawn args   '-I',
	gyp info spawn args   '/Users/robgordon/.node-gyp/0.12.0/common.gypi',
	gyp info spawn args   '-Dlibrary=shared_library',
	gyp info spawn args   '-Dvisibility=default',
	gyp info spawn args   '-Dnode_root_dir=/Users/robgordon/.node-gyp/0.12.0',
	gyp info spawn args   '-Dmodule_root_dir=/Users/robgordon',
	gyp info spawn args   '--depth=.',
	gyp info spawn args   '--no-parallel',
	gyp info spawn args   '--generator-output',
	gyp info spawn args   'build',
	gyp info spawn args   '-Goutput_dir=.' ]
	gyp: binding.gyp not found (cwd: /Users/robgordon) while trying to load binding.gyp
	gyp ERR! configure error
	gyp ERR! stack Error: `gyp` failed with exit code: 1
	gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/node-gyp/lib/configure.js:343:16)
	gyp ERR! stack     at ChildProcess.emit (events.js:110:17)
	gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:1067:12)
	gyp ERR! System Darwin 13.4.0
	gyp ERR! command "node" "/usr/local/bin/node-gyp" "configure"
	gyp ERR! cwd /Users/robgordon
	gyp ERR! node -v v0.12.0
	gyp ERR! node-gyp -v v1.0.3
	gyp ERR! not ok

**Comment by rob-gordon** [comment]
Hmmm.. anyhow I switched to an earlier version of node and had no problem installing. I think there may be some things mixed up in my brew-installed node and nvm, etc... Thanks for your help!
